apiVersion: batch/v1
kind: Job
metadata:
  name: archive-service
  labels:
    app: archive-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: archive-service
  template:
    metadata:
      labels:
        app: archive-service
    spec:
      containers:
        - name: archive-service
          image: archive-service:0.1
          imagePullPolicy: IfNotPresent
          env:
            - name: ES_HOST
              value: "elasticsearch"
            - name: ES_PORT
              value: "9200"
          volumeMounts:
            - name: archive-logs
              mountPath: /app/logs
      restartPolicy: Always
      volumes:
        - name: archive-logs
          emptyDir: {}
